import sys
import os

def usage():
    print("Usage: python3 context_patch.py <target_file> <search_pattern_file> <replacement_file>")
    sys.exit(1)
    
# Generated by Google AI studio Gemini 3 model (free trial) as one of the possibilities for the prompt
# "The general way in which the linux patch command works is that it needs the input file to not change - 
# if the input file gets an excess line or something like that, patch will fail. Please write a script 
# which can replace the first instance of a particular text with another, 
# where the initial and final text can be multiline, in a particular file."

if len(sys.argv) != 4:
    usage()

target_path = sys.argv[1]
search_path = sys.argv[2]
replace_path = sys.argv[3]

# Check if files exist
if not os.path.exists(target_path):
    print(f"Error: Target file '{target_path}' not found.")
    sys.exit(1)

# Read the files
try:
    with open(target_path, 'r') as f:
        content = f.read()
    
    with open(search_path, 'r') as f:
        search_text = f.read()
        
    with open(replace_path, 'r') as f:
        replace_text = f.read()

    # Perform replacement
    # We strip trailing newlines from the search/replace files optionally 
    # if your editor adds them automatically, but usually exact match is safer.
    
    if search_text not in content:
        print("Error: Search block not found in target file. No changes made.")
        sys.exit(1)

    # Replace only the first occurrence
    new_content = content.replace(search_text, replace_text, 1)

    with open(target_path, 'w') as f:
        f.write(new_content)
        
    print(f"Successfully patched {target_path}")

except Exception as e:
    print(f"An error occurred: {e}")
    sys.exit(1)